## Практическая 2

### Вариант 12

1. Создать случайную матрицу 2x10 целых чисел от 1 до 2 и определить, есть ли в массиве нулевые столбцы. Программа должна вернуть индексы нулевых колонок, либо выдать сообщение об их отсутствии.

In [19]:
import numpy as np

np.random.seed(12)

a = np.random.randint(3, size=(2, 10))

print(a, end="\n\n")

columns = list()
for i in range(len(a[0])):
    if a[0][i] == 0 and a[1][i] == 0:
        columns.append(i)

if columns:
    print("Нулевые столбцы:", end=" ")
    print(*columns)
else:
    print("Нулевых столбцов нет")

[[2 1 1 2 0 0 2 1 0 1]
 [1 1 2 2 2 0 1 0 0 1]]

Нулевые столбцы: 5 8


2. Создайте произвольную матрицу 3x3 и нормализуйте ее.

In [34]:
np.random.seed(12)

a = np.random.randint(12, size=(3, 3))
print(a, end="\n\n")

a = a / np.linalg.norm(a)

print("Нормализованная матрица:")
print(a)

[[11 11  6]
 [ 1  2  3]
 [ 3  0  6]]

Нормализованная матрица:
[[0.59920818 0.59920818 0.32684083]
 [0.05447347 0.10894694 0.16342041]
 [0.16342041 0.         0.32684083]]


Известны номера n серверов, к которым были адресованы последние m запросов.
Так же известно время ответа каждого сервера на запрос (в секундах).
Необходимо написать программу, которая определит суммарное и среднее время
ответа каждого сервера из n серверов на отправленные ему запросы.
Исходные данные:
можно присвоить любые целые значения
m – кол-во последних запросов к серверам
n – кол-во серверов
Номера серверов, к которым были адресованы последние m запросов и время
ответов серверов на последние m запросов сгенерировать случайным образом исходя из
заданных значений m и n.